# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      
      
      - uses: actions/checkout@v2
      - name: android lint statistics
      # You may pin to the exact commit or the version.
      # uses: MeilCli/android-lint-statistics@c99d3826b3742c43bd435eb26b10b46945368394
     uses: MeilCli/android-lint-statistics@v1.0.0
      with:
    # running repository, format: owner/repository
    repository: # default is ${{ github.repository }}
    # github token, using to push data branch
    github_token: # default is ${{ github.token }}
    # android lint reported xml file paths, enable glob pattern
    lint_xml_file_path: 
    # android lint reported xml file paths glob pattern`s follow symbolic links option
    lint_xml_file_path_follow_symbolic_links: # default is false
    # the saving data branch, this branch is created by this action. if want disable this feature, put empty string
    data_branch: # optional, default is data/lint
    # the saving data commit user
    data_commit_user: # optional, default is github-action
    # the saving data commit user`s email
    data_commit_email: # optional, default is 41898282+github-actions[bot]@users.noreply.github.com
    # the saving data json file path, this file is created at data branch
    data_json_file_path: # optional, default is data.json
    # the data transition chart png image path, this file is created at your checkouted branch
    data_chart_file_path: # optional, default is data.png
    # the severity chart png image path, this file is created at your checkouted branch
    severity_chart_file_path: # default is severity.png
    # the priority chart png image path, this file is created at your checkouted branch
    priority_chart_file_path: # default is priority.png
    # the report json file path, this file is created at your checkouted branch
    report_json_file_path: # default is report.json
    # the report text file path, this file is created at your checkouted branch
    report_text_file_path: # default is report.txt

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
